### ISSUE TITLE
Hamming Code Table Attribution

### ISSUE THREAD

**Issue by dmstuffer** [777arc/textbook#23]
While editing the Channel Coding chapter, the table laying out parity bits appears to be an image of a table I saw in the [Wikipedia page on Hamming Codes](https://en.wikipedia.org/wiki/Hamming_code). Is it a screen capture of the table in that Wikipedia page? If so, you may want to provide an attribution.

**Comment by 777arc** [comment]
Ah yes good catch.  This textbook was based on my course's lecture slides (made 3 years ago), and like most professors I do a lot of copy/pasting of images from online since it's just taught to a small class for educational purposes only, and even though I recreated most of them over time, I forget that there are ones that I didn't recreate.  I'll go ahead and recreate it instead of giving attribution =P

**Comment by dmstuffer** [comment]
Hah, I remember those days when I taught freshman composition. Memes for days. My students would call that out since I was teaching them how to cite sources. Yay, learning!

**Comment by 777arc** [comment]
Also, for an image to be uploaded and used on wikipedia it must have a fair-use license that must permit both commercial reuse and derivative works.  Not sure if that allows me to use it the way I am, but at least it's better than just copying it from another similar textbook =P

**Comment by 777arc** [comment]
Done!  https://pysdr.org/content/channel_coding.html#hamming-code

**Comment by dmstuffer** [comment]
Gorgeous!
