### ISSUE TITLE
Ubuntu Install Problem

### ISSUE THREAD

**Issue by jamesterrance** [777arc/textbook#43]
Using the script given here: https://pysdr.org/content/pluto.html
The step 'sudo python3 setup.py.cmakein install' installs Python 3.6, but version 3.7+ is required, so the script errors out on the last step.  Researching the issue, it appears uninstalling 3.6 is not recommended.  Is there a workaround for this?
Thanks,
Jim D

**Comment by 777arc** [comment]
Can you trying using `python3 setup.py install` instead of that line that errors out?

If that doesn't work try wiping away your libiio directory and reclone it with version 0.15 instead, its older and I believe my class was on Ubuntu 18 at the time:

git clone --branch v0.15 https://github.com/analogdevicesinc/libiio.git

Now I'm not sure if you'll also have to grab older versions of the other two libraries, but if you do try to grab a release from around Fall 2018 or a little before.

**Comment by 777arc** [comment]
might have to be `sudo python3 setup.py install` for you
